[conf]
default-lang = "en"

[lang.en]
title = "CV of Dominik Schwaiger"
education = "Education"
now = "now"
bsc_inf = "Bachelor Computer Science"
ksw = "Cantonal School Wattwil"
zurich = "Zurich"
main_subject = "Focus on Physics und Application of Mathematics"
experience = "Experience"
intern_dev = "Intern in Development"
december = "December"
frontend = "Frontend with Angular and Bootstrap"
backend = "Backend with Spring Boot and Apache POI"
deploy = "Deploying new Projects using Docker"
intern_cs = "Intern CS"
october = "October"
working_space = "Setting up of Workspaces"
additional = "Additional Experience"
cs_school = "CS-School 61 Frauenfeld"
july = "July"
rs = "Recruit School Telematics Soldier"
skills = "Skills"
languages = "Languages"
german = "German"
mother_tongue = "Native"
english = "English"
french = "French"
basic_knowledge = "Basic Knowledge"
cs_langs = "Programming Languages and Frameworks"
source = "Source"
version_of = "Date:"
november = "November"
unsw = "UNSW"
sydney = "Sydney"
september = "September"
february = "February"
exchange = "Exchange Semester"

[lang.de]
title = "Lebenslauf von Dominik Schwaiger"
education = "Ausbildung"
now = "jetzt"
bsc_inf = "Bachelor Informatik"
ksw = "Kantonsschule Wattwil"
zurich = "Zürich"
main_subject = "Schwerpunkt Physik und Anwendungen der Mathematik"
experience = "Berufserfahrung"
intern_dev = "Praktikant in der Entwicklung"
december = "Dezember"
frontend = "Frontend mit Angular und Bootstrap"
backend = "Backend mit Spring Boot und Apache POI"
deploy = "Deployen von neuen Projekten mit Docker"
intern_cs = "Praktikant Informatik"
october = "Oktober"
working_space = "Einrichten von Arbeitsplätzen"
additional = "Weitere Erfahrungen"
cs_school = "Informatikschule 61 Frauenfeld"
july = "Juli"
rs = "Rekrutenschule Telematiksoldat"
skills = "Fähigkeiten"
languages = "Sprachen"
german = "Deutsch"
mother_tongue = "Muttersprache"
english = "Englisch"
french = "Französisch"
basic_knowledge = "Grundkenntnisse"
cs_langs = "Programmiersprachen und Frameworks"
source = "Quelle"
version_of = "Version vom"
november = "November"
unsw = "UNSW"
sydney = "Sydney"
september = "September"
february = "Februar"
exchange = "Austauschsemester"